# Generated by Django 5.0.7 on 2026-04-28
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0002_schema_alignment"),
    ]

    operations = [
        migrations.AddField(
            model_name="grade",
            name="status",
            field=models.CharField(
                blank=True,
                choices=[("pass", "Pass"), ("failed", "Failed")],
                max_length=10,
                null=True,
            ),
        ),
    ]
