# Generated by Codex on 2026-05-02
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0003_grade_status"),
    ]

    operations = [
        migrations.AddField(
            model_name="grade",
            name="period",
            field=models.CharField(default="current", max_length=20),
        ),
        migrations.AlterField(
            model_name="grade",
            name="grade_type",
            field=models.CharField(
                choices=[
                    ("final", "Final"),
                    ("exam", "Exam"),
                    ("assignment", "Assignment"),
                    ("quiz", "Quiz"),
                ],
                default="final",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="grade",
            name="grade_value",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                max_digits=4,
                null=True,
                validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(20)],
            ),
        ),
        migrations.AddConstraint(
            model_name="grade",
            constraint=models.UniqueConstraint(
                fields=("student", "subject", "period"),
                name="uniq_grade_student_subject_period",
            ),
        ),
    ]
