# Generated by Django 5.0.7 on 2026-05-03 09:44

from datetime import date

import django.db.models.deletion
from django.db import migrations, models


def bootstrap_current_enrollment(apps, schema_editor):
    AcademicYear = apps.get_model("users", "AcademicYear")
    Student = apps.get_model("users", "Student")
    StudentEnrollment = apps.get_model("users", "StudentEnrollment")

    current_year = AcademicYear.objects.filter(is_current=True).order_by("-starts_on", "-id").first()
    if not current_year:
        current_year, _ = AcademicYear.objects.get_or_create(
            code="legacy-current",
            defaults={
                "label": "Legacy current year",
                "starts_on": date(2025, 9, 1),
                "ends_on": date(2026, 7, 15),
                "is_current": True,
            },
        )
    else:
        AcademicYear.objects.filter(is_current=True).exclude(id=current_year.id).update(is_current=False)
        if not current_year.is_current:
            current_year.is_current = True
            current_year.save(update_fields=["is_current"])

    for student in Student.objects.all():
        if student.student_class_id is None and student.study_year is None:
            continue
        StudentEnrollment.objects.update_or_create(
            student=student,
            academic_year=current_year,
            defaults={
                "student_class_id": student.student_class_id,
                "study_year": student.study_year,
                "is_active": True,
            },
        )


def noop_reverse(apps, schema_editor):
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_grade_period_constraints'),
    ]

    operations = [
        migrations.CreateModel(
            name='AcademicYear',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('code', models.CharField(max_length=20, unique=True)),
                ('label', models.CharField(max_length=50)),
                ('starts_on', models.DateField()),
                ('ends_on', models.DateField()),
                ('is_current', models.BooleanField(default=False)),
            ],
            options={
                'db_table': 'academic_years',
                'ordering': ['-starts_on', '-id'],
            },
        ),
        migrations.CreateModel(
            name='ClassSubjectCurriculum',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('coefficient_override', models.DecimalField(blank=True, decimal_places=2, max_digits=4, null=True)),
                ('is_required', models.BooleanField(default=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('academic_year', models.ForeignKey(db_column='academic_year_id', on_delete=django.db.models.deletion.CASCADE, related_name='curriculum_items', to='users.academicyear')),
                ('student_class', models.ForeignKey(db_column='class_id', on_delete=django.db.models.deletion.CASCADE, related_name='curriculum_items', to='users.class')),
                ('subject', models.ForeignKey(db_column='subject_id', on_delete=django.db.models.deletion.CASCADE, related_name='curriculum_items', to='users.subject')),
            ],
            options={
                'db_table': 'class_subject_curriculum',
                'ordering': ['student_class_id', 'academic_year_id', 'subject_id'],
            },
        ),
        migrations.CreateModel(
            name='StudentEnrollment',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('study_year', models.IntegerField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('academic_year', models.ForeignKey(db_column='academic_year_id', on_delete=django.db.models.deletion.CASCADE, related_name='enrollments', to='users.academicyear')),
                ('student', models.ForeignKey(db_column='student_id', on_delete=django.db.models.deletion.CASCADE, related_name='enrollments', to='users.student')),
                ('student_class', models.ForeignKey(blank=True, db_column='class_id', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='enrollments', to='users.class')),
            ],
            options={
                'db_table': 'student_enrollments',
                'ordering': ['-academic_year__starts_on', '-id'],
            },
        ),
        migrations.AddConstraint(
            model_name='classsubjectcurriculum',
            constraint=models.UniqueConstraint(fields=('student_class', 'academic_year', 'subject'), name='uniq_curriculum_class_year_subject'),
        ),
        migrations.AddConstraint(
            model_name='studentenrollment',
            constraint=models.UniqueConstraint(fields=('student', 'academic_year'), name='uniq_enrollment_student_year'),
        ),
        migrations.RunPython(bootstrap_current_enrollment, noop_reverse),
    ]
